version: "3.7"

services: 
    gcloud_pipeline: 
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports: 
            - 8080:8080
        working_dir: /app
    database:
        image: "postgres"
        env_file:
            - .env
        volumes:
            - database-data:/var/lib/postgresql/data/
        
volumes:
    database-data: 