version: "3.7"

services: 
    gcloud_pipeline: 
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports: 
            - '3000:3000'
        working_dir: /AIR-TABLE

#networks:
 #   default:
  #      external:
   #             name: gcloud_pipeline