# This is a basic workflow to help you get started with Actions

name: AB-learn-github-actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # install node on the runner
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      # run our node app components
      - name: Install Dependencies (CI)
        run: npm ci
        
      - name: Initiate Build
        run: CI=false npm run build --if-present
        
      - name: Run Test Suite
        run: npm test      
      
      # get secret
      - name: retrieve secret
        env:
          super_secret: ${{secrets.SECRET_NAME}}
        run:
          echo $super_secret
    
  publish:
    needs: build
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      
      - name: get version and tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
      - name: create docker image
        run: docker build . --no-cache -t ablackmagic1/node-app:${{steps.get_version.outputs.VERSION }}
      
    
    

