# This is a basic workflow to help you get started with Actions

name: AB-Test-Zone

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  name: setup environment variables
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: gcloud_pipeline
  
  publish:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      
      # get secret
      - name: test variables
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run:
          echo $PROJECT_ID
          
      # Connect to GCP
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_KEY }}
          
      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    
    

